In [16]:
import numpy as np
labels = np.load("rochester_label.npy")

In [17]:
y=labels[:,0]

In [18]:
y

array([1., 2., 1., ..., 1., 1., 1.])

In [19]:
y[y>1]=2

In [20]:
labels[:,0]=y

In [21]:
labels[:,0]

array([1., 2., 1., ..., 1., 1., 1.])

In [22]:
np.save('rochester_label_faculty_bin.npy',labels)

In [25]:
y=labels[:,-1]
np.unique(y)

from collections import Counter
Counter(y)


Counter({0.0: 418,
         1.0: 1,
         2.0: 1,
         3.0: 1,
         4.0: 1,
         5.0: 1,
         6.0: 1,
         7.0: 1,
         8.0: 2,
         9.0: 1,
         10.0: 2,
         11.0: 7,
         12.0: 29,
         13.0: 131,
         14.0: 615,
         15.0: 764,
         16.0: 811,
         17.0: 908,
         18.0: 860,
         19.0: 8})

In [26]:
y[y<14]=0

In [27]:
y[y==19]=0

In [28]:
y=y-13

In [31]:
y[y==-13]=0

In [34]:
Counter(y)
labels[:,-1]=y

In [35]:
np.save('rochester_label_faculty_bin.npy',labels)

In [1]:
import numpy as np
labels = np.load("yale_label.npy")

In [3]:
y = labels[:,0]

In [5]:
np.unique(y) 

array([0., 1., 2., 3., 4., 5.])

In [6]:

from collections import Counter
Counter(y)


Counter({0.0: 3, 1.0: 5479, 2.0: 2333, 3.0: 68, 4.0: 55, 5.0: 640})

In [7]:
y[y>1]=2